# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24759f42d94a325fd82e80eddeea8b6feea86756d799a9f577548dcf5eb570d3f422bf671e34ab3b8ee28dcb640df8a4f5eda74852d0754d7bc27f3d4f16d9d

test:
  secret_key_base: 1990c9247bf4b2b944685c33edfa767b9863e1392f99fbed11a485fbd796a3834c22885e14c10f93ed276ac34f9adc20b6498a231400489891ca8e56bc1d7ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
